apiVersion: v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicaSet # we only support replicaSet now
    metadata:
      name: rs
  metrics:
    MemoryUtilizationUsage: 0.2 # 0.2 means target is 0.2Gi
  scaleInterval: 25