apiVersion: v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicaSet # we only support replicaSet now
    metadata:
      name: function-get_ip-rs
  metrics:
    CPUUtilizationPercentage: 70
  scaleInterval: 30