apiVersion: v1
kind: ReplicaSet
metadata:
  name: function-get_ip-rs
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: function-get_ip-label
  template:
    metadata:
      labels:
        app: function-get_ip-label
    spec:
      containers:
        - name: function-get_ip-container
          image: 192.168.1.15:5000/function-get_ip:latest
          ports:
            - name: function-port
              containerPort: 8080
