apiVersion: v1
kind: Pod
metadata:
  name: prometheus_pod
  namespace: default
  labels:
    log: prometheus
spec:
  restartPolicy: Always
  containers:
    - name: prometheus
      image: 192.168.1.15:5000/my_ubuntu_with_go_and_test
      ports:
        - name: prometheus
          containerPort: 2112
          hostPort: 2112
      volumeMounts:
        - name: volume
          mountPath: /data
  volumes:
    - name: volume
      hostPath:
        path: /pod