apiVersion: v1
kind: Pod
metadata:
  name: prometheus_pod
  namespace: default
  labels:
    app: nginx
    log: prometheus
spec:
  restartPolicy: Always
  containers:
    - name: viewer
      image: dplsming/nginx-fileserver:1.0
      ports:
        - containerPort: 80
          hostPort: 8888
      volumeMounts:
        - name: volume
          mountPath: /usr/share/nginx/html/files
    - name: prometheus
      image: ubuntu:20.04
      ports:
        - name: prometheus
          containerPort: 2331
          hostPort: 2331
        - name: nginx
          containerPort: 6880
          hostPort: 6880
      volumeMounts:
        - name: volume
          mountPath: /data
  volumes:
    - name: volume
      hostPath:
        path: /pod