kind: Service
apiVersion: v1
metadata:
  name: dns-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: hello
  ports:
    - name: hello-port
      port: 1234
      targetPort: hello
      protocol: TCP 