kind: Service
apiVersion: v1
metadata:
  name: dns-service2
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: hello
  ports:
    - name: hello-port
      port: 2345
      targetPort: hello
      protocol: TCP