kind: Service
apiVersion: v1
metadata:
  name: dns-service2
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: hello2
  ports:
    - name: hello-port
      port: 2345
      targetPort: hello2
      protocol: TCP