apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: default
  labels:
    app: hello
spec:
  restartPolicy: Always
  containers:
    - name: helloContainer
      image: strm/helloworld-http
      ports:
        - name: hello
          containerPort: 80
          hostPort: 80
      volumeMounts:
        - name: volume
          mountPath: /data
  volumes:
    - name: volume
      hostPath:
        path: /pod