apiVersion: v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicaSet # we only support replicaSet now
    metadata:
      name: rs
  metrics:
    MemoryUtilizationUsage: 1.0 # 1.0 means target is 1.0Gi
  scaleInterval: 25