apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: default
  labels:
    app: hello
spec:
  restartPolicy: Always
  containers:
    - name: helloContainer
      image: ubuntu:20.04
      ports:
        - name: hello
          containerPort: 6800
          hostPort: 6800
      volumeMounts:
        - name: volume
          mountPath: /data
  volumes:
    - name: volume
      hostPath:
        path: /pod