apiVersion: v1
kind: Service
metadata:
  name: HelloService2
  namespace: default
spec:
  selector:
    app: hello
  type: NodePort
  ports:
    - name: HelloPort
      protocol: TCP
      port: 23456 # 对外暴露的端口
      targetPort: hello # 转发的端口的名字，pod对应的端口名字