apiVersion: v1
kind: Service
metadata:
  name: HelloService
  namespace: default
spec:
  selector:
    app: hello
  type: ClusterIP
  ports:
    - name: HelloPort
      protocol: TCP
      port: 12345 # 对外暴露的端口
      targetPort: hello # 转发的端口的名字，pod对应的端口名字